ALTER TABLE public.workspace_chat_user_profiles
  ADD COLUMN IF NOT EXISTS last_interaction_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS is_visible BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS has_focus BOOLEAN NOT NULL DEFAULT TRUE;

